name = "dotfiles"
id = "17504290032302696503"
default = "desktop"
systems = ["desktop", "laptop"]

[[links]]
name = "backgrounds"
destination = "$HOME/backgrounds"
src = "backgrounds"

[[links]]
name = ".config/nvim"
destination = "$HOME/.config/nvim"
src = ".config/nvim"

[[links]]
name = ".config/alacritty.yml"
destination = "$HOME/.config/alacritty.yml"
src = ".config/alacritty.yml"

[[links]]
name = ".config/rofi"
destination = "$HOME/.config/rofi.old"
src = ".config/rofi"

[[links]]
name = ".config/picom"
destination = "$HOME/.config/picom"
src = ".config/picom"

[[links]]
name = ".config/starship.toml"
destination = "$HOME/.config/starship.toml"
src = ".config/starship.toml"

[[links]]
name = "xmonad-config/my-xmonad.cabal"
destination = "$HOME/.xmonad/my-xmonad.cabal"
src = "xmonad-config/my-xmonad.cabal"

[[links]]
name = "xmonad-config/stack.yaml"
destination = "$HOME/.xmonad/stack.yaml"
system = "desktop"
src = "xmonad-config/stack.yaml"

[[links]]
name = "xmonad-config/lib"
destination = "$HOME/.xmonad/lib"
src = "xmonad-config/lib"

[[links]]
name = "xmonad"
destination = "$HOME/.xmonad/xmonad.hs"
system = "desktop"
src = "xmonad-config/lib/xmonad.hs"

[[links]]
name = "flake"
destination = "$HOME/.xmonad/flake.nix"
src = "xmonad-config/flake.nix"

[[links]]
name = "flake lock"
destination = "$HOME/.xmonad/flake.lock"
src = "xmonad-config/flake.lock"

[[links]]
name = ".config/polybar/config.ini"
destination = "$HOME/.config/polybar/config.ini"
src = ".config/polybar/config.ini"

[[links]]
name = ".config/polybar/launch_desktop.sh"
destination = "$HOME/.config/polybar/launch.sh"
default_path = ".config/polybar/launch_desktop.sh"

[links.source_map]
laptop = ".config/polybar/launch_laptop.sh"

[[links]]
name = ".config/polybar/scripts"
destination = "$HOME/.config/polybar/scripts"
src = ".config/polybar/scripts"

[[links]]
name = "xmonad-config/build"
destination = "$HOME/.xmonad/build"
default_path = "xmonad-config/build_laptop"

[links.source_map]
desktop = "xmonad-config/build_desktop"

[[links]]
name = "xmonad-config/screenshot-sec.sh"
destination = "$HOME/.xmonad/screenshot-sec.sh"
src = "xmonad-config/screenshot-sec.sh"

[[links]]
name = ".config/fontconfig"
destination = "$HOME/.config/fontconfig"
src = ".config/fontconfig"

[[links]]
name = "xmonad-config/my-xmonad_laptop.cabal"
destination = "$HOME/.xmonad/my-xmonad.cabal"
default_path = "xmonad-config/my-xmonad.cabal"

[links.source_map]
laptop = "xmonad-config/my-xmonad_laptop.cabal"

[[links]]
name = "dotfiles"
destination = "$HOME/.zshrc"
src = ".zshrc"

[[links]]
name = "dotfiles"
destination = "$HOME/.tmux"
src = ".tmux"

[[links]]
name = "dotfiles"
destination = "$HOME/.tmux.conf.local"
src = ".tmux.conf.local"

[[links]]
name = ".tmux"
destination = "$HOME/.tmux.conf"
src = ".tmux/tmux.conf"

[[links]]
name = ".config/dunst"
destination = "$HOME/.config/dunst"
src = ".config/dunst"

[[links]]
name = "phoebelyrics"
destination = "$HOME/Music/phoebe"
src = "phoebelyrics"

[[links]]
name = ".config/rofi_themed"
destination = "/home/auscyber/.config/rofi"
src = ".config/rofi_themed"

[[links]]
name = "fetch"
destination = "$HOME/.local/bin/fetch"
src = "fetch"

[[links]]
name = "nix-vscode"
destination = "/home/auscyber/nix-vscode"
src = "nix-vscode"

[[links]]
name = "setIcon.sh"
destination = "/home/auscyber/setIcon.sh"
src = "setIcon.sh"

[[links]]
name = "wezterm"
destination = "/home/auscyber/.config/wezterm"
src = ".config/wezterm"

[[links]]
name = "nitrogen"
destination = "/home/auscyber/.config/nitrogen"
src = ".config/nitrogen"

[[links]]
name = "fetch_home"
src = "fetch"
destination = "$HOME/fetch"
