name = "dotfiles"
id = "17504290032302696503"
systems = []

[[links]]
name = "ghost.png"
src = "$HOME/backgrounds/ghost.png"
destination = "ghost.png"

[[links]]
name = ".config/nvim"
src = "$HOME/.config/nvim"
destination = ".config/nvim"

[[links]]
name = ".config/alacritty.yml"
src = "$HOME/.config/alacritty.yml"
destination = ".config/alacritty.yml"

[[links]]
name = ".config/polybar"
src = "$HOME/.config/polybar"
destination = ".config/polybar"

[[links]]
name = ".config/rofi"
src = "$HOME/.config/rofi"
destination = ".config/rofi"

[[links]]
name = ".config/picom"
src = "$HOME/.config/picom"
destination = ".config/picom"

[[links]]
name = ".config/starship.toml"
src = "$HOME/.config/starship.toml"
destination = ".config/starship.toml"

[[links]]
name = "xmonad/my-xmonad.cabal"
src = "$HOME/.xmonad/my-xmonad.cabal"
destination = "xmonad/my-xmonad.cabal"

[[links]]
name = "xmonad/stack.yaml"
src = "$HOME/.xmonad/stack.yaml"
destination = "xmonad/stack.yaml"

[[links]]
name = "xmonad/lib"
src = "$HOME/.xmonad/lib"
destination = "xmonad/lib"

[[links]]
name = "xmonad"
src = "$HOME/.xmonad/xmonad.hs"
destination = "xmonad"
