name = "dotfiles"
id = "17504290032302696503"
default = "desktop"
systems = ["desktop", "laptop"]

[[links]]
name = "backgrounds"
src = "$HOME/backgrounds"
destination = "backgrounds"

[[links]]
name = ".config/nvim"
src = "$HOME/.config/nvim"
destination = ".config/nvim"

[[links]]
name = ".config/alacritty.yml"
src = "$HOME/.config/alacritty.yml"
destination = ".config/alacritty.yml"

[[links]]
name = ".config/rofi"
src = "$HOME/.config/rofi.old"
destination = ".config/rofi"

[[links]]
name = ".config/picom"
src = "$HOME/.config/picom"
destination = ".config/picom"

[[links]]
name = ".config/starship.toml"
src = "$HOME/.config/starship.toml"
destination = ".config/starship.toml"

[[links]]
name = "xmonad/my-xmonad.cabal"
src = "$HOME/.xmonad/my-xmonad.cabal"
destination = "xmonad/my-xmonad.cabal"

[[links]]
name = "xmonad/stack.yaml"
src = "$HOME/.xmonad/stack.yaml"
destination = ["desktop", "xmonad/stack.yaml"]

[[links]]
name = "xmonad/lib"
src = "$HOME/.xmonad/lib"
destination = "xmonad/lib"

[[links]]
name = "xmonad"
src = "$HOME/.xmonad/xmonad.hs"
destination = ["desktop", "xmonad/lib/xmonad.hs"]

[[links]]
name = ".config/polybar/config.ini"
src = "$HOME/.config/polybar/config.ini"
destination = ".config/polybar/config.ini"

[[links]]
name = ".config/polybar/launch_desktop.sh"
src = "$HOME/.config/polybar/launch.sh"

[links.destination]
desktop = ".config/polybar/launch_desktop.sh"
laptop = ".config/polybar/launch_laptop.sh"

[[links]]
name = ".config/polybar/scripts"
src = "$HOME/.config/polybar/scripts"
destination = ".config/polybar/scripts"

[[links]]
name = "xmonad/build"
src = "$HOME/.xmonad/build"

[links.destination]
laptop = "xmonad/build_laptop"
desktop = "xmonad/build_desktop"

[[links]]
name = "xmonad/screenshot-sec.sh"
src = "$HOME/.xmonad/screenshot-sec.sh"
destination = "xmonad/screenshot-sec.sh"

[[links]]
name = ".config/fontconfig"
src = "$HOME/.config/fontconfig"
destination = ".config/fontconfig"

[[links]]
name = "xmonad/my-xmonad_laptop.cabal"
src = "$HOME/.xmonad/my-xmonad.cabal"

[links.destination]
desktop = "xmonad/my-xmonad.cabal"
laptop = "xmonad/my-xmonad_laptop.cabal"

[[links]]
name = "dotfiles"
src = "$HOME/.zshrc"
destination = ".zshrc"

[[links]]
name = "dotfiles"
src = "$HOME/.tmux"
destination = ".tmux"

[[links]]
name = "dotfiles"
src = "$HOME/.tmux.conf.local"
destination = ".tmux.conf.local"

[[links]]
name = ".tmux"
src = "$HOME/.tmux.conf"
destination = ".tmux/tmux.conf"

[[links]]
name = ".config/dunst"
src = "$HOME/.config/dunst"
destination = ".config/dunst"

[[links]]
name = "phoebelyrics"
src = "$HOME/Music/phoebe"
destination = "phoebelyrics"

[[links]]
name = ".config/rofi_themed"
src = "/home/auscyber/.config/rofi"
destination = ".config/rofi_themed"
