
format = """
[┌───────────────────>](bold green)
[│](bold green) $directory$custom $username$rust$package$cmd_duration$git_status$nix_shell
$character"""

[custom.shell]
command = "echo $STARSHIP_SHELL"
when = "true"
format  = "[$output](bold blue)"

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[└─➜ ](bold green)"
error_symbol = "[└─➜ ](bold red)"


[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true


# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10


# Don't print a new line at the start of the prompt

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
